-- 코드를 작성해주세요
SELECT
  YEAR(DIFFERENTIATION_DATE) AS YEAR,
  MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY AS YEAR_DEV,
  ID
FROM
  ECOLI_DATA
ORDER BY YEAR, YEAR_DEV;

-- 윈도우 함수 안쓰는 쿼리
SELECT
  e.ID,
  YEAR(e.DIFFERENTIATION_DATE) AS YEAR,
  (m.MAX_SIZE - e.SIZE_OF_COLONY) AS YEAR_DEV
FROM
  ECOLI_DATA e
JOIN (
  SELECT
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    MAX(SIZE_OF_COLONY) AS MAX_SIZE
  FROM
    ECOLI_DATA
  GROUP BY
    YEAR(DIFFERENTIATION_DATE)
) m
  ON YEAR(e.DIFFERENTIATION_DATE) = m.YEAR
ORDER BY
  YEAR, YEAR_DEV;
